os: linux
dist: bionic
language: node_js
arch:
 - amd64
 - ppc64le

.addons: &AIRTAP
  sauce_connect: true
  hosts:
    - airtap.local

jobs:
  include:
    - name: Run tests on stable Node.js
      node_js: stable
      script: npm test
    - name: Run tests on Node.js 12
      node_js: 12
      script: npm test
    - name: Run tests on Node.js 10
      node_js: 10
      script: npm test
    - name: Run tests on Node.js 8
      node_js: 8
      script: npm test
    - name: Run tests on Node.js 6
      node_js: 6
      script: npm test
    - name: Run tests on Node.js 4
      node_js: 4
      script: npm test
    - name: Run tests on Node.js 0.12
      node_js: '0.12'
      script: npm test
    - name: Run tests on Node.js 0.10
      node_js: '0.10'
      script: npm test
    - name: Run browser tests
      node_js: lts/*
      script: npm run test:browsers
      addons: *AIRTAP
    - name: Run browser tests with polyfilled environment
      node_js: lts/*
      script: npm run test:browsers:with-polyfills
      addons: *AIRTAP

env:
  global:
  - secure: AdUubswCR68/eGD+WWjwTHgFbelwQGnNo81j1IOaUxKw+zgFPzSnFEEtDw7z98pWgg7p9DpCnyzzSnSllP40wq6AG19OwyUJjSLoZK57fp+r8zwTQwWiSqUgMu2YSMmKJPIO/aoSGpRQXT+L1nRrHoUJXgFodyIZgz40qzJeZjc=
  - secure: heQuxPVsQ7jBbssoVKimXDpqGjQFiucm6W5spoujmspjDG7oEcHD9ANo9++LoRPrsAmNx56SpMK5fNfVmYediw6SvhXm4Mxt56/fYCrLDBtgGG+1neCeffAi8z1rO8x48m77hcQ6YhbUL5R9uBimUjMX92fZcygAt8Rg804zjFo=
